config/routes.rb
GsanBatchManager::Application.routes.draw do

  resource :processos, only: :none do
    get :filtrar
    post :configura
    post :get_cronograma_info
    post :pesquisar_setores_comerciais
    post :pesquisar_rotas
  end

  resources :processos

  namespace :admin do
    resources :processos, only: [:index, :update]
  end

  resource :pesquisar, only: :none, controller: 'pesquisar' do
    get :processos
    get :usuarios
    get :situacoes
  end

  # post :reiniciar_atividade, controller: :processos, action: :reiniciar_atividade

  post 'reiniciar_atividade/:id', to: 'processos#reiniciar_atividade', as: 'reiniciar_atividade'

  # post "/processos/reiniciar_atividade/:id"

  post :inserir_batch, controller: :batch

  get :autenticar_usuario, :controller => 'usuarios', :action => 'autenticar_usuario'

  get :logout, :controller => 'usuarios', :action => 'logout'

  root to: "processos#index"
end

app/models/processo.rb
class Processo < ActiveRecord::Base
  self.table_name='batch.processo'
  self.primary_key='proc_id'

  belongs_to :periodicidade, class_name: 'ProcessoTipo', foreign_key: 'prtp_id'
  has_many :processos_iniciados, class_name: 'ProcessoIniciado', foreign_key: 'proc_id'
  has_many :atividades, class_name: "ProcessoAtividade", foreign_key: 'proc_id'

  alias_attribute "id", "proc_id"
  alias_attribute "nome", "proc_dsprocesso"
  alias_attribute "ultima_alteracao", "proc_tmultimaalteracao"
  alias_attribute "prioridade", "proc_prioridade"
  alias_attribute "limite", "proc_limite"
  alias_attribute "arquivo_batch", "proc_nmarquivobatch"

  scope :finalizacao, -> { where(arquivo_batch: 'job_parar_batch').first }

  def inicia_processo params={}
    klass = Kernel.const_get params[:nome_batch].split('_').map {|w| w.capitalize }.join('')
    klass.new(self, params).inicia_processo
  end

  def self.pesquisar_grupo_cronograma(grupos)
    if grupos.blank?
      @grupos_cronograma = []
      grupos ||= FaturamentoGrupo.all
    end

    get_grupos_cronograma(grupos)
  end

  def self.get_grupos_cronograma(grupos)
    grupos.each do |grupo|
      @grupos_cronograma << grupo if FaturamentoGrupoCronogramaMensal.possui_faturamento_grupo?(grupo)
    end

    @grupos_cronograma.sort_by { |faturamento_grupo| faturamento_grupo.id }
  end
end

app/controllers/admin/processos_controller.rb
class Admin::ProcessosController < ApplicationController
  def index
    @processos = Processo.all.order("proc_prioridade DESC").page params[:page]
  end

  def update
    processo = Processo.find(params[:id])

    if processo.update_attributes(processo_params)
      processo.periodicidade = ProcessoTipo.find(params[:periodicidade])
      if processo.save
        flash[:notice] = "Configurações atualizadas com sucesso!"
        redirect_to admin_processos_path
      else
        flash[:error] = "Erro ao atualizar configurações!"
        redirect_to admin_processos_path
      end
    else
      flash[:error] = "Erro ao atualizar configurações!"
      redirect_to admin_processos_path
    end
  end

  private

  def processo_params
    params.require(:processo).permit([:prioridade, :limite, :arquivo_batch])
  end
end

app/controllers/processos_controller.rb
class ProcessosController < ApplicationController

  include ApplicationHelper

  before_action :get_processos, except: [:show]

  def index
  end

  def show
    @processo = ProcessoIniciado.find(params[:id])
  end

  def new
    @setores_comerciais = SetorComercial.all.sort_by {|setor| setor.id }
  end

  def update
    @processo = ProcessoIniciado.find(params[:id])

    reiniciar_processo @processo
  end

  def configura
    @grupos = Processo.pesquisar_grupo_cronograma(nil).map { |g| [g.descricao, g.id] }
  end

  def filtrar
    begin
      @processos = @processos.joins(:processo).where("processo.proc_dsprocesso LIKE ?", "%#{params[:processo]}%") unless params[:processo].blank?
      @processos = @processos.joins(:usuario).where("usuario.usur_nmusuario LIKE ?", "%#{params[:usuario]}%") unless params[:usuario].blank?
      @processos = @processos.where("processo_iniciado.proi_nngrupo = ?", params[:grupo]) unless params[:grupo].blank?
      @processos = @processos.where("processo_iniciado.proi_tminicio >= ?", params[:data_processo_inicio]) unless params[:data_processo_inicio].blank?
      @processos = @processos.where("processo_iniciado.proi_tmtermino <= ?", params[:data_processo_final]) unless params[:data_processo_final].blank?

      @total = @processos.count
      @processos.page params[:page]

      render :index
    rescue => e
      logger.warn "Problemas nos parâmetros: #{params} - #{e}"

      flash[:error] = "Problemas para executar a sua pesquisa, certifique-se que os parâmetros estão corretos"
      redirect_to root_path
    end
  end

  def destroy
    @processo = ProcessoIniciado.find(params[:id])

    if @processo.cancelar
      flash[:notice] = "O processo ##{@processo.id} entrou em processo de cancelamento da execução."
      redirect_to processo_path(@processo.id)
    else
      flash[:error] = "Ocorreu um erro ao tentar cancelar o processo (##{@processo.id})."
      render :show
    end
  end

  def get_cronograma_info
    grupo_faturamento = FaturamentoGrupo.find(params[:grupo_faturamento])

    @rotas = Rota.codigos_rota_por_grupo(grupo_faturamento)
    @setores_comerciais = Rota.setor_comercial_por_grupo(grupo_faturamento)
    
    @localidades = [["Selecione a localidade (Opcional)", 0]]
    @localidades.concat SetorComercial.localidades_por_setores_comerciais(@setores_comerciais)

    respond_to do |format|
      format.js
      format.json {
        render :json => {
          ano_mes_referencia: grupo_faturamento.ftgr_amreferencia,
          data_vencimento: grupo_faturamento.data_vencimento_formatada
        }
      }
    end
  end

  def pesquisar_setores_comerciais
    @rotas = []
    if params[:localidade].empty?
      @setores_comerciais = []
    else
      @setores_comerciais = SetorComercial.joins(:rotas).where(:loca_id => params[:localidade], :rota => {:ftgr_id => params[:grupo_faturamento]})
      @setores_comerciais = @setores_comerciais.map{ |s| [s.stcm_cdsetorcomercial, s.id] }.uniq
      @setores_comerciais.insert(0, ["Selecione o setor comercial (Opcional)", 0])
    end

    respond_to do |format|
      format.js
    end
  end

  def pesquisar_rotas
    if params[:setor_comercial].empty?
      @rotas = []
    else
      @rotas = []
      localidade = SetorComercial.find(params[:setor_comercial]).localidade
      rotas = Rota.where(
        :setor_comercial => params[:setor_comercial],
        :indicador_uso => Rota::IndicadorUso[:ativado],
        :faturamento_grupo => params[:faturamento_grupo]
        ).sort_by {|rota| rota.rota_cdrota }

      rotas.each do |r|
        arquivos_gerados = ArquivoTextoRoteiroEmpresa.where(rota_id: r.id, ano_mes_referencia: params[:ano_mes_referencia], loca_id: localidade.id, ftgr_id: params[:faturamento_grupo])

        if not arquivos_gerados.empty?
          if (1..2).include?(arquivos_gerados.map(&:sitl_id)[0])
            @rotas << r
          end
        else
          @rotas << r
        end
      end


      @rotas = @rotas.map { |r| [r.codigo_rota, r.id] }
      @rotas.insert(0, ["Selecione uma rota (Opcional)",0])

    end

    respond_to do |format|
      format.js
    end
  end

  def reiniciar_atividade
    controle_processo = ControleProcessoAtividade.find(params[:id])
    processo_iniciado = ProcessoIniciado.find(controle_processo.proi_id)

    reiniciar_processo processo_iniciado, [controle_processo]
  end

  private

  def reiniciar_processo(processo, atividades = [])
    deletar_log processo

    if processo.reiniciar atividades
      flash[:notice] = "Processo reiniciado com sucesso!"
      redirect_to processo_path(processo)
    else
      flash[:error] = "Erro ao reiniciar processo!"
      render :show
    end
  end

  def adicionar_processo_parametro(nome_parametro, valor_parametro, processo_iniciado)
    novo_parametro = ProcessoParametro.new
    novo_parametro.nome = nome_parametro
    novo_parametro.valor = valor_parametro
    novo_parametro.temporario = ProcessoParametro::TEMPORARIO[:sim]
    novo_parametro.processo_iniciado = processo_iniciado

    novo_parametro.save!
  end

  def get_processos
    @filtros = params
    @filtros[:situacao] ||= ""

    if @filtros[:situacao].empty?
      @processos = ProcessoIniciado.send("todos").page params[:page]
    else
      metodo_situacao = @filtros[:situacao].downcase.strip.gsub(" ", "_").gsub("[\.]", "")
      @processos = ProcessoIniciado.send(metodo_situacao).page params[:page]
    end

    @total = @processos.count
  end
end

app/helpers/processos_helper.rb
module ProcessosHelper
  def active?(situacao, situacao_selecionada)
    situacao == situacao_selecionada ? "active" : ""
  end

  def calcula_percentual_atividade(atividade)
    return 0 unless atividade

    total       = atividade.total_itens
    processados = atividade.itens_processados

    return 0 if total.blank? or processados.blank? or total == 0

    ((processados / total.to_f) * 100).ceil
  end
end

app/views/processos/_novo_processo.html.erb
<div class="row">
  <div class="col-md-10">
    <% if novo_processo %>
      <%= form_tag inserir_batch_path, class: "form-horizontal", role: "form" do |f| %>
        <%= render partial: template_processo(novo_processo), locals: { f: f, processo: novo_processo, klass: get_arquivo_batch(novo_processo) } rescue render partial: 'templates/default', locals: { processo: novo_processo } %>
      <% end %>
    <% end %>
  </div>
</div>

app/views/processos/_processos.html.erb
<div class="table-responsive">
  <div class="panel panel-default">
    <div class="panel-heading">Processos</div>
    <center>
      <%= paginate processos %>
    </center>
    <table class="table table-striped">
      <thead>
        <tr>
          <th>#</th>
          <th>Processo</th>
          <th>Grupo</th>
          <th>Início</th>
          <th>Término</th>
          <th>Usuário</th>
          <th></th>
          <th></th>
        </tr>
      </thead>
      <tbody>
      <% processos.each do |processo| %>
        <tr>
          <td><%= processo.id %></td>
          <td><%= processo.nome %></td>
          <td><%= processo.grupo unless processo.grupo.blank? %></td>
          <td><%= processo.hora_inicio.strftime('%d/%m/%Y %H:%M:%S') unless processo.hora_inicio.blank? %></td>
          <td><%= processo.hora_termino.strftime('%d/%m/%Y %H:%M:%S') unless processo.hora_termino.blank? %></td>
          <td><%= processo.usuario.nome %></td>
          <td><%= link_to "Detalhes", processo_path(processo), class: "btn btn-primary" %></td>
          <td><%= link_to "X", processo_path(processo.id), method: :delete, title: "Cancelar Processo", class: "btn btn-danger", data: {confirm: "Você tem certeza que deseja parar o processo?"} unless processo.parado? %></td>
        </tr>
      <% end %>
      </tbody>
    </table>
    <center>
      <%= paginate processos %>
    </center>
  </div>
</div>

app/views/processos/configura.js.erb
$('#novo-processo').html("<%= escape_javascript(render partial: 'novo_processo', locals: { novo_processo: @filtros[:novo_processo] }) %>")

app/views/processos/get_cronograma_info.js.erb
$('#localidades').html("<%= escape_javascript(options_for_select(@localidades)) %>");
$('#setores_comerciais').html("<%= escape_javascript(options_for_select([])) %>");
$('#id_rota').html("<%= escape_javascript(options_for_select([])) %>");

app/views/processos/index.html.erb
<div class="page-header">
  <%= build_breadcrumb [
    { title: "Processos", active: true },
  ] %>

  <div class="actions pull-right">
    <%= build_header_button('novo', :processo, new_processo_path) %>
  </div>
  <h1>Consulta de Processos</h1>
</div>

<div class="row">
  <div class="col-md-6">
    <%= form_tag filtrar_processos_path, method: :get, class: "form-horizontal", role: "form" do |f| %>
      <div class="form-group">
        <%= label_tag "Processo", nil, class: "col-sm-2 control-label" %>
        <div class="col-sm-8">
          <%= text_field_tag :processo, params[:term], id: "processos-search", placeholder: "tipo de processo", class: "form-control" %>
        </div>
      </div>
      <div class="form-group">
        <%= label_tag "Usuário", nil, class: "col-sm-2 control-label" %>
        <div class="col-sm-8">
          <%= text_field_tag :usuario, params[:term], id: "usuarios-search", placeholder: "nome do usuário", class: "form-control" %>
        </div>
      </div>
      <div class="form-group">
        <%= label_tag "Grupo", nil, class: "col-sm-2 control-label" %>
        <div class="col-sm-8">
          <%= text_field_tag :grupo, '', placeholder: "número do grupo", class: "form-control" %>
        </div>
      </div>
      <div class="form-group">
        <%= label_tag "Início", nil, class: "col-sm-2 control-label" %>
        <div class="col-sm-8">
          <div class='input-group date datetimepicker'>
            <%= text_field_tag :data_processo_inicio, '', :'data-format' => "dd/MM/yyyy hh:mm:ss", placeholder: "dd/mm/aaaa hh:mm:ss", class: "form-control" %>
            <span class="input-group-addon"><span class="glyphicon glyphicon-calendar"></span>
            </span>
          </div>
        </div>
      </div>
      <div class="form-group">
        <%= label_tag "Término", nil, class: "col-sm-2 control-label" %>
        <div class="col-sm-8">
          <div class='input-group date datetimepicker'>
            <%= text_field_tag :data_processo_final, '', :'data-format' => "dd/MM/yyyy hh:mm:ss", placeholder: "dd/mm/aaaa hh:mm:ss", class: "form-control" %>
            <span class="input-group-addon"><span class="glyphicon glyphicon-calendar"></span>
            </span>
          </div>
        </div>
      </div>
      <div class="form-group">
        <%= label_tag "Situação", nil, class: "col-sm-2 control-label" %>
        <div class="col-sm-8">
          <%= select_tag :situacao, options_from_collection_for_select(ProcessoSituacao.all, "descricao", "descricao"), include_blank: true, class: "form-control" %>
        </div>
      </div>
      <div class="form-group">
        <div class="col-sm-offset-2 col-sm-10">
          <%= button_tag "Pesquisar", class: "btn btn-primary" %>
        </div>
      </div>
    <% end %>
  </div>
  <div class="col-md-6">
    <div class="panel panel-default">
      <div class="panel-heading"><%= @filtros[:situacao] %></div>
      <center>
        <h3>Total</h3>
        <h1>
          <%= @total %>
          <small>processos</small>
        </h1>
      </center>
      <ul class="list-group">
        <% if not @filtros[:processo].blank? %>
          <li class="list-group-item">
            <strong>Processo</strong>
            <span><%= @filtros[:processo] %></span>
          </li>
        <% end %>
        <% if not @filtros[:usuario].blank? %>
          <li class="list-group-item">
            <strong>Usuário</strong>
            <span><%= @filtros[:usuario] %></span>
          </li>
        <% end %>
        <% if not @filtros[:grupo].blank? %>
          <li class="list-group-item">
            <strong>Grupo</strong>
            <span><%= @filtros[:grupo] %></span>
          </li>
        <% end %>
        <% if not @filtros[:data_processo_inicio].blank? %>
          <li class="list-group-item">
            <strong>Início</strong>
            <span><%= @filtros[:data_processo_inicio] %></span>
          </li>
        <% end %>
        <% if not @filtros[:data_processo_final].blank? %>
          <li class="list-group-item">
            <strong>Final</strong>
            <span><%= @filtros[:data_processo_final] %></span>
          </li>
        <% end %>
      </ul>
    </div>
  </div>
</div>
<hr/>
<%= render partial: "processos", locals: { processos: @processos } unless @processos.blank? %>

app/views/processos/new.html.erb
<div class="page-header">
  <%= build_breadcrumb [
    { title: "Processos", link: processos_path },
    { title: "Novo Processo", active: true }
  ] %>

  <h1>Novo Processo</h1>
</div>

<div class="row">
  <div class="col-md-10">
    <%= form_tag configura_processos_path, class: "form-horizontal", role: "form", remote: true do |f| %>
      <div class="form-group">
        <%= label_tag "Processo", nil, class: "col-sm-2 control-label" %>
        <div class="col-sm-6">
          <%= text_field_tag :novo_processo, params[:term], id: "novo-processo-search", placeholder: "tipo de processo", class: "form-control" %>
        </div>
        <div class="col-sm-2">
          <%= button_tag "Configurar", class: "btn btn-primary" %>
        </div>
      </div>
    <% end %>
  </div>
</div>
<div id="novo-processo">
  <%= render partial: 'novo_processo', locals: { novo_processo: params[:novo_processo] } %>
</div>

app/views/processos/pesquisar_rotas.js.erb
$('#id_rota').html("<%= escape_javascript(options_for_select(@rotas)) %>");

app/views/processos/pesquisar_setores_comerciais.js.erb
$('#setores_comerciais').html("<%= escape_javascript(options_for_select(@setores_comerciais)) %>");
$('#id_rota').html("<%= escape_javascript(options_for_select(@rotas)) %>");

app/views/processos/show.html.erb
<div class="page-header">
  <%= build_breadcrumb [
    { title: "Processos", link: processos_path },
    { title: "#{@processo.nome}", active: true }
  ] %>

  <h1>Informações do Processo</h1>
</div>

<div id="refresh">
  <div id="infos-processo">
    <div class="panel panel-default">
      <div class="panel-heading">Informações Gerais</div>
      <center>
        <h3><%= @processo.nome %></h3>
      </center>

      <ul class="list-group">
        <li class="list-group-item">
          <strong>Id:</strong>
          <span><%= @processo.id %></span>
        </li>
        <% if not @processo.usuario.nome.blank? %>
          <li class="list-group-item">
            <strong>Usuário:</strong>
            <span><%= @processo.usuario.nome %></span>
          </li>
        <% end %>
        <% if not @processo.grupo.blank? %>
          <li class="list-group-item">
            <strong>Grupo:</strong>
            <span><%= @processo.grupo unless @processo.grupo.blank? %></span>
          </li>
        <% end %>
        <% if not @processo.hora_inicio.blank? %>
          <li class="list-group-item">
            <strong>Início:</strong>
            <span><%= @processo.hora_inicio.strftime('%d/%m/%Y %H:%M:%S') %></span>
          </li>
        <% end %>
        <% if not @processo.hora_termino.blank? %>
          <li class="list-group-item">
            <strong>Final:</strong>
            <span><%= @processo.hora_termino.strftime('%d/%m/%Y %H:%M:%S') %></span>
          </li>
        <% end %>
        <% if not @processo.situacao.blank? %>
          <li class="list-group-item">
            <strong>Situação:</strong>
            <span><%= @processo.situacao.descricao %></span>
          </li>
        <% end %>
        <% if not @processo.parametros.blank? %>
          <li class="list-group-item">
            <strong>Parâmetros:</strong>
            <ul>
              <% @processo.parametros.each do |parametro| %>
                <% if not parametro.nome == "percentualProcessado" %>
                  <li><span><strong><%= "#{parametro.nome}" %></strong><%= " = #{parametro.valor}" %></span></li>
                <% end %>
              <% end %>
            </ul>
          </li>
        <% end %>
        <li class="list-group-item">
          <% @processo.atividades_exibidas.each do |atividade| %>
            <%= link_to "", reiniciar_atividade_path(atividade.id), method: :post, title: "Reiniciar atividade", class: "glyphicon glyphicon-refresh reiniciar-atividade" if @processo.parado? %>
            <strong><%= atividade.descricao.capitalize %></strong>
            <div class="progress">
              <div class="progress-bar" role="progressbar" aria-valuenow="<%= calcula_percentual_atividade(atividade) %>" aria-valuemin="0" aria-valuemax="100" style='<%= "width: #{calcula_percentual_atividade(atividade)}%;" %>'>
                <%= calcula_percentual_atividade(atividade) %>%
              </div>
            </div>
          <% end %>
        </li>
        <li class="list-group-item">
          <span><%= link_to "Reiniciar", processo_path(@processo.id), method: :put, class: "btn btn-primary" if @processo.parado? %></span>
          <span><%= link_to "Cancelar Processo", processo_path(@processo.id), method: :delete, class: "btn btn-danger", data: {confirm: "Você tem certeza que deseja parar o processo?"} unless @processo.parado? %></span>
          <span><%= link_to "Voltar", root_path, class: "btn btn-default" %></span>
        </li>
      </ul>
    </div>
    <% if @processo.em_processamento? %>
      <div class="panel panel-default">
        <div class="panel-heading">Log de Execução</div>
        <ul class="list-group">
          <li class="list-group-item">
            <%= simple_format log_processo(@processo) %>
          </li>
        </ul>
      </div>
    <% end %>
  </div>
</div>