config/routes.rb
GsanBatchManager::Application.routes.draw do

  resource :processos, only: :none do
    get :filtrar
    post :configura
    post :get_cronograma_info
    post :pesquisar_setores_comerciais
    post :pesquisar_rotas
  end

  resources :processos

  namespace :admin do
    resources :processos, only: [:index, :update]
  end

  resource :pesquisar, only: :none, controller: 'pesquisar' do
    get :processos
    get :usuarios
    get :situacoes
  end

  # post :reiniciar_atividade, controller: :processos, action: :reiniciar_atividade

  post 'reiniciar_atividade/:id', to: 'processos#reiniciar_atividade', as: 'reiniciar_atividade'

  # post "/processos/reiniciar_atividade/:id"

  post :inserir_batch, controller: :batch

  get :autenticar_usuario, :controller => 'usuarios', :action => 'autenticar_usuario'

  get :logout, :controller => 'usuarios', :action => 'logout'

  root to: "processos#index"
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>GsanBatchManager</title>
  <%= stylesheet_link_tag "application", :media => "all" %>
  <%= csrf_meta_tags %>
</head>
<body>
  <div class="wrapper" >
    <nav class="top">
      <div class="container-fluid">
        <div class="row">
          <div class="col-md-4">
            <%= link_to root_application_path do %>
              <i class="fa fa-align-justify fa-2x"></i>
            <% end -%>
          </div>
          <div class="col-md-4 brand">
            <span class="brand">
              <%= link_to root_application_path do %>
                <i class="fa fa-tint"></i>GSAN
              <% end %>
            </span>
          </div>
          <div class="col-md-4">
            <ul class="top-nav">
              <li class="dropdown">
                <div class="dropdown-toggle dropdown-user" id="dropdownMenu1" data-toggle="dropdown">
                  <%= @usuario_logado.nome %>
                  <span class="caret"></span>
                </div>
                <ul class="dropdown-menu" aria-labelledby="dropdownMenu1">
                  <li>
                    <%= link_to admin_processos_path do %>
                      <i class="fa fa-cog"></i> Configurações
                    <% end %>
                  </li>
                </ul>
              </li>
            </ul>
          </div>
        </div>
      </div>
    </nav>
    <div class="col-md-12 main">
      <div class="container">
        <%= render partial: "shared/flash_messages", flash: flash %>
        <%= yield %>
      </div>
    </div>
  </div>
  <%= javascript_include_tag "application" %>
  <script type="text/javascript">
    var BASE_URL = "<%= ENV['URL_BASE'] %>";

    $('.datetimepicker').datetimepicker({
      language: 'pt-BR'
    });

    setInterval("setTimeout();", 5000);
    function setTimeout(){
      $('#refresh').load(location.href + ' #infos-processo');
    }

    $(document).ready(function(){
      $("#processos-search").autocomplete({source: '/pesquisar/processos.json'})
      $("#novo-processo-search").autocomplete({source: '/pesquisar/processos.json'})
      $("#usuarios-search").autocomplete({source: '/pesquisar/usuarios.json'})
    });
  </script>
</body>
</html>